[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
acceleratorinator-sys = { version = "0.1.0", path = "../acceleratorinator-sys" }
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
