[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA --always-print-stacktrace --catch-hardfault --catch-reset"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["panic_abort", "core"]
build-std-features = ["optimize_for_size"]
