[package]
name = "acceleratorinator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]

[build-dependencies]
cbindgen = "0.27"

[profile.release]
opt-level = 3
debug = true
